security:
    enable_authenticator_manager: true
    hide_user_not_found: false

    providers:
        custom_user_provider:
            id: App\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            logout:
                path: app.logout
                target: app.login

    access_control:
        - { path: ^/login|^/unauthorized, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: [ROLE_USER] }